apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-get-task-api
  template:
    metadata:
      labels:
        app: todo-get-task-api
    spec:
      containers:
      - name: todo-get-task-api
        image: akscon101.azurecr.io/todo-get-task-api:v1
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:mysqlservertittu123.database.windows.net,1433;Database=mysqldatabase;Uid=Tattu01!@@mysqlservertittu123;Pwd=Tattu!12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
          

